### ISSUE TITLE
Profile: Contact me button label not aligned correctly

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla-iam/dino-park-issues#164] opened 2019-10-30 11:30 UTC
The "Contact me" button is not aligned correctly:

<img width="308" alt="Screenshot 2019-10-30 at 12 30 22" src="https://user-images.githubusercontent.com/330324/67854704-b666a080-fb08-11e9-984b-4b65b0e54d26.png">

**Comment by fiji-flo** [comment] 2019-10-30 12:51
I cannot reproduce it unless I change the font size for that element. Anything custom in your setup?

**Comment by MichaelKohler** [comment] 2019-10-30 12:58
I had the font size in Firefox at Times/14px and my display setting set to "scaled" for the whole OS on macOS. Reverting both changes doens't help much though. This is on latest Firefox Nightly.

<img width="486" alt="Screenshot 2019-10-30 at 13 55 15" src="https://user-images.githubusercontent.com/330324/67859906-9c32bf80-fb14-11e9-85de-f26940673540.png">

<img width="378" alt="Screenshot 2019-10-30 at 13 58 10" src="https://user-images.githubusercontent.com/330324/67860083-f3389480-fb14-11e9-9e33-9605a0f9590a.png">

**Comment by fiji-flo** [comment] 2019-10-30 13:04
Yeah, looks like it's the font size. Can you set it to 16 to see if that works? I'll look into a fix.

**Comment by MichaelKohler** [comment] 2019-10-30 13:35
> Yeah, looks like it's the font size. Can you set it to 16 to see if that works? I'll look into a fix.

Sorry for not being clear, I already had done that before taking those screenshots.

**Comment by fiji-flo** [comment] 2019-10-30 14:35
https://github.com/mozilla-iam/dino-park-front-end/pull/494

I you still have a setup to run this there's a new version of the extension: https://github.com/fiji-flo/dinoparklocaldev/releases/tag/0.0.9
Doesn't work in nightly due to https://bugzilla.mozilla.org/show_bug.cgi?id=1590898

**Comment by fiji-flo** [comment] 2019-11-01 08:30
To reproduce change the settings in about:preferences → Language and Appearance to 10 or 32.

**Comment by fiji-flo** [comment] 2019-11-05 17:26
Should be fixed.

**Closed as completed by fiji-flo** 2019-11-05 17:26 UTC
