### ISSUE TITLE
Clicking the Accounts edit icon mis-positions the viewport

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/dino-park-issues#57] opened 2019-04-10 21:10 UTC
[Here's a video of the problem](https://youtu.be/iW8zFSbofHs).

Clicking the edit icon shouldn't move the viewport away from what needs to be edited.

**Comment by hmitsch** [comment] 2019-04-11 08:55
@viorelaioia @rleitan do we have a Jira issue for this already?

**Comment by hmitsch** [comment] 2019-04-11 11:24
Issue could be successfully reproduced.

**Comment by hmitsch** [comment] 2019-04-11 11:24
Cross-reference: https://jira.mozilla.com/browse/DP-1224 (sorry, this sits behind Mozilla IAM).

**Comment by fiji-flo** [comment] 2019-04-18 11:35
@gene1wood I was about to tackle this but I cannot reproduce it. Is it still happening for you?

**Comment by gene1wood** [comment] 2019-04-18 11:40
Ya, I also can't, I wonder what commit fixed this over the past week

**Comment by viorelaioia** [comment] 2019-04-25 16:37
@gene1wood , this issue is fixed in prod.

**Closed by viorelaioia** 2019-04-25 16:37 UTC
Labels: Jira'ized
