### ISSUE TITLE
Unable to verify Bugzilla as an identity

### ISSUE THREAD

**Issue by pdehaan** [mozilla-iam/dino-park-issues#113] opened 2019-07-01 17:43 UTC
Unable to verify Bugzilla as an identity, it gives me the following error in devtools console:

> Refused to send form data to 'https://people.mozilla.org/' because it violates the following Content Security Policy directive: "form-action 'self' https://www.google.com/search".

![Server_error](https://user-images.githubusercontent.com/557895/60456626-91136580-9bee-11e9-81a8-39c579252d7f.png)

**Comment by fiji-flo** [comment] 2019-07-01 18:30
That was using Firefox or something else. I'm aware that it currently does now work in webkit/blink due to https://bugzilla.mozilla.org/show_bug.cgi?id=1557735

**Comment by flaki** [comment] 2019-07-01 21:14
FWIW this worked in latest Nightly for me just now.

**Comment by pdehaan** [comment] 2019-07-01 22:51
Ah, I was probably using Chrome since thats what my Gmail was in.
I'll try in Firefox Nightly.

**Comment by pdehaan** [comment] 2019-07-02 21:15
Verified this worked in Nightly and I was able to get Bugzilla verified. Thanks.

**Comment by spoji** [comment] 2019-10-31 18:11
I can reproduce this issue as a NDA contributor. Using Chrome 77.0

**Comment by LeoMcA** [comment] 2019-10-31 18:44
This is a Chrome/Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1557735

Closing as invalid.

**Closed as completed by LeoMcA** 2019-10-31 18:44 UTC
Labels: invalid
